project 'RCTMultipleImagePicker.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RCTMultipleImagePicker' do
  pod 'TZImagePickerController', '1.5.0'
  pod 'React', :path => '../../react-native'
end