project 'ios.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RCTMultipleImagePicker' do
  pod 'TZImagePickerController', '1.4.5'
  pod 'React', :path => '../../liaoyuan-app/liaoyuanApp/node_modules/react-native'
end